# Generated by Django 5.2.18 on 2026-10-07 20:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('value', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='note')),
                ('graded_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='notée le')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades_entered', to=settings.AUTH_USER_MODEL, verbose_name='saisie par')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school', verbose_name='école')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academics.sequence', verbose_name='séquence')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academics.student', verbose_name='élève')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academics.subject', verbose_name='matière')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ['sequence', 'subject', 'student'],
                'indexes': [models.Index(fields=['sequence', 'subject'], name='grade_sequence_subject_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'subject', 'sequence'), name='grade_student_subject_sequence_unique'), models.CheckConstraint(condition=models.Q(('value__gte', 0), ('value__lte', 20)), name='grade_value_range')],
            },
        ),
    ]
