# Generated by Django 5.2.18 on 2026-10-07 20:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100, verbose_name='action')),
                ('entity_type', models.CharField(max_length=100, verbose_name="type d'entité")),
                ('entity_id', models.CharField(max_length=64, verbose_name="identifiant de l'entité")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='tenants.school', verbose_name='école')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "journal d'audit",
                'verbose_name_plural': "journaux d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'created_at'], name='auditlog_school_created_idx')],
            },
        ),
    ]
