# Generated by Django 5.2.18 on 2026-10-07 20:42

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('last_name', models.CharField(max_length=150, verbose_name='nom')),
                ('first_name', models.CharField(max_length=150, verbose_name='prénom')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir entre 8 et 15 chiffres (espaces autorisés, « + » initial optionnel).', regex='^\\+?[0-9 ]{8,15}$')], verbose_name='téléphone')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super administrateur'), ('SCHOOL_ADMIN', "Administrateur d'école"), ('TEACHER', 'Enseignant'), ('PARENT', 'Parent'), ('CASHIER', 'Caissier')], max_length=20, verbose_name='rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='accès admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='inscrit le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenants.school', verbose_name='école')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['last_name', 'first_name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='user_email_lower_unique'), models.CheckConstraint(condition=models.Q(models.Q(('role', 'SUPER_ADMIN'), ('school__isnull', True)), models.Q(models.Q(('role', 'SUPER_ADMIN'), _negated=True), ('school__isnull', False)), _connector='OR'), name='user_super_admin_has_no_school')],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
