# Generated by Django 5.2.18 on 2026-10-07 20:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'niveau',
                'verbose_name_plural': 'niveaux',
                'ordering': ['school', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('number', models.PositiveSmallIntegerField(verbose_name='numéro')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
            ],
            options={
                'verbose_name': 'séquence',
                'verbose_name_plural': 'séquences',
                'ordering': ['academic_year', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('matricule', models.CharField(max_length=30, verbose_name='matricule')),
                ('last_name', models.CharField(max_length=150, verbose_name='nom')),
                ('first_name', models.CharField(max_length=150, verbose_name='prénom')),
                ('birth_date', models.DateField(verbose_name='date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='sexe')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'élève',
                'verbose_name_plural': 'élèves',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('relationship', models.CharField(blank=True, choices=[('FATHER', 'Père'), ('MOTHER', 'Mère'), ('TUTOR', 'Tuteur'), ('OTHER', 'Autre')], max_length=10, verbose_name='lien de parenté')),
            ],
            options={
                'verbose_name': 'lien élève/tuteur',
                'verbose_name_plural': 'liens élève/tuteur',
                'ordering': ['student', 'guardian'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('coefficient', models.PositiveSmallIntegerField(verbose_name='coefficient')),
            ],
            options={
                'verbose_name': 'matière',
                'verbose_name_plural': 'matières',
                'ordering': ['classroom', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('last_name', models.CharField(max_length=150, verbose_name='nom')),
                ('first_name', models.CharField(max_length=150, verbose_name='prénom')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir entre 8 et 15 chiffres (espaces autorisés, « + » initial optionnel).', regex='^\\+?[0-9 ]{8,15}$')], verbose_name='téléphone')),
                ('language_section', models.CharField(choices=[('FR', 'Français'), ('EN', 'Anglais')], max_length=2, verbose_name='section linguistique')),
                ('monthly_salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='salaire mensuel (FCFA)')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'enseignant',
                'verbose_name_plural': 'enseignants',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('label', models.CharField(max_length=20, verbose_name='libellé')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archivée')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school', verbose_name='école')),
            ],
            options={
                'verbose_name': 'année scolaire',
                'verbose_name_plural': 'années scolaires',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='academics.academicyear', verbose_name='année scolaire')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school', verbose_name='école')),
            ],
            options={
                'verbose_name': 'classe',
                'verbose_name_plural': 'classes',
                'ordering': ['academic_year', 'level__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomTeacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('section', models.CharField(choices=[('FR', 'Français'), ('EN', 'Anglais')], max_length=2, verbose_name='section linguistique')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_teachers', to='academics.classroom', verbose_name='classe')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school', verbose_name='école')),
            ],
            options={
                'verbose_name': 'affectation enseignant/classe',
                'verbose_name_plural': 'affectations enseignant/classe',
                'ordering': ['classroom', 'section'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.academicyear', verbose_name='année scolaire')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.classroom', verbose_name='classe')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school', verbose_name='école')),
            ],
            options={
                'verbose_name': 'inscription',
                'verbose_name_plural': 'inscriptions',
                'ordering': ['academic_year', 'classroom', 'student'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('last_name', models.CharField(max_length=150, verbose_name='nom')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='prénom')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir entre 8 et 15 chiffres (espaces autorisés, « + » initial optionnel).', regex='^\\+?[0-9 ]{8,15}$')], verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school', verbose_name='école')),
            ],
            options={
                'verbose_name': 'parent/tuteur',
                'verbose_name_plural': 'parents/tuteurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
