# Generated by Django 5.2.18 on 2026-10-07 20:42

import apps.core.db
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Nécessaire pour les ExclusionConstraint ci-dessous (index GiST sur
        # une colonne d'égalité combinée à un chevauchement d'intervalle).
        # Peut nécessiter un rôle disposant du droit de créer des extensions
        # sur l'hébergeur PostgreSQL cible (à vérifier sur Render).
        BtreeGistExtension(),
        migrations.AddField(
            model_name='guardian',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL, verbose_name='compte utilisateur'),
        ),
        migrations.AddField(
            model_name='level',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school', verbose_name='école'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='academics.level', verbose_name='niveau'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequences', to='academics.academicyear', verbose_name='année scolaire'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school', verbose_name='école'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school', verbose_name='école'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.student', verbose_name='élève'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_guardians', to='academics.guardian', verbose_name='parent/tuteur'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school', verbose_name='école'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_guardians', to='academics.student', verbose_name='élève'),
        ),
        migrations.AddField(
            model_name='subject',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.classroom', verbose_name='classe'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school', verbose_name='école'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school', verbose_name='école'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='compte utilisateur'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.teacher', verbose_name='enseignant'),
        ),
        migrations.AddField(
            model_name='classroomteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_teachers', to='academics.teacher', verbose_name='enseignant'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('school', 'label'), name='academicyear_school_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='academicyear_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', True), ('is_archived', True), _negated=True), name='academicyear_not_active_and_archived'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school',), name='academicyear_one_active_per_school'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('school', '='), (apps.core.db.DateRange('start_date', 'end_date', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=True)), '&&')], name='academicyear_no_date_overlap'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='level_school_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('school', 'order'), name='level_school_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='classroom_academic_year_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='sequence',
            constraint=models.UniqueConstraint(fields=('academic_year', 'number'), name='sequence_academic_year_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='sequence',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 6)), name='sequence_number_range'),
        ),
        migrations.AddConstraint(
            model_name='sequence',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='sequence_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='sequence',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('academic_year', '='), (apps.core.db.DateRange('start_date', 'end_date', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=True)), '&&')], name='sequence_no_date_overlap'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'matricule'), name='student_school_matricule_unique'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year'), name='enrollment_student_academic_year_unique'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(fields=('student', 'guardian'), name='studentguardian_student_guardian_unique'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('classroom', 'name'), name='subject_classroom_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('coefficient__gte', 1)), name='subject_coefficient_min_1'),
        ),
        migrations.AddConstraint(
            model_name='classroomteacher',
            constraint=models.UniqueConstraint(fields=('classroom', 'section'), name='classroomteacher_classroom_section_unique'),
        ),
        migrations.AddConstraint(
            model_name='classroomteacher',
            constraint=models.UniqueConstraint(fields=('classroom', 'teacher'), name='classroomteacher_classroom_teacher_unique'),
        ),
    ]
