# Generated by Django 5.2.18 on 2026-10-07 20:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('city', models.CharField(max_length=100, verbose_name='ville')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/', verbose_name='logo')),
                ('plan', models.CharField(choices=[('STARTER', 'Starter'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='STARTER', max_length=20, verbose_name='formule')),
                ('currency', models.CharField(default='XAF', max_length=3, verbose_name='devise')),
                ('timezone', models.CharField(default='Africa/Douala', max_length=50, verbose_name='fuseau horaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'école',
                'verbose_name_plural': 'écoles',
                'ordering': ['name'],
            },
        ),
    ]
